name: Deploy con Llaves Secretas
on:
  push:
    branches: [ main ] # Se ejecuta cuando subes algo a la rama principal

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar código
        uses: actions/checkout@v4

      - name: 2. Crear archivo config.js desde Secretos
        run: |
          echo "${{ secrets.CONFIG_JS_CONTENT }}" > config.js
        # Esto crea el archivo físicamente en el servidor temporal de GitHub

      - name: 3. Publicar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Sube todo el contenido actual
          branch: gh-pages # Lo publica en una rama especial para la web
